using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace WinMovieRack.Model.Enums {
    public enum TodoType {
        INSERT_MOVIE_BY_IMDB_ID, INSERT_FULL_MOVIE, INSERT_MOVIE, INSERT_PERSON, UPDATE_SOFT_INFORMATION, UPDATE_SOFT_INFORMATION_OF_MOVIE, UPDATE_SOFT_INFORMATION_OF_PERSON, UPDATE_SOFT_INFORMATION_OF_ALL_MOVIES, UPDATE_SOFT_INFORMATION_OF_ALL_PERSONS
    }
}
